changesetIgnorePatterns:
  - .yarn/cache/**

nodeLinker: node-modules

npmAlwaysAuth: true

npmPublishAccess: restricted

npmRegistryServer: 'https://artifactory.ops.babylontech.co.uk/artifactory/api/npm/babylon-virtual-npm/'

yarnPath: .yarn/releases/yarn-3.2.3.cjs
