name: 'API Governance Verification'
description: 'Perform API governance directly within the subgraph repo.'
author: 'Babylon'
inputs: 
  myInput:
    description: 'Input to use'
    default: 'world'
runs:
  using: 'docker'
  image: 'Dockerfile'